### PR TITLE
IONe v1.0.0 Base

### PR DESCRIPTION
**Pull request by slntopp**
Very first independent release. Features down in comments

### CODE REVIEW

**Comment by slntopp** [comment]
At this point:
* Detaching IONe from Sunstone
* Both ONe and IONe APIs and dev tools support
* Separate IONe configuration UI
* IONe App support
* IONe needed hooks installer new hooks-subsystem support

**Review by ione-cloud — APPROVED** [review]

**Comment by slntopp** [comment]
* State hooks updated to API hooks
* UI is ready to use

**Comment by slntopp** [comment]
Added nginx configuration task, see #28

**Comment by slntopp** [comment]
Installer successfully tested on `OpenNebula 5.12.0.3`

**Pull request merged**
